<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Evidence_Locker</RootNamespace>
    <AssemblyName>Evidence_Locker</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Evidence_Locker.Core\Evidence_Locker.Core.csproj" />
    <ProjectReference Include="..\Evidence_Locker.Data\Evidence_Locker.Data.csproj" />
    <ProjectReference Include="..\Evidence_Locker.Services\Evidence_Locker.Services.csproj" />
    <ProjectReference Include="..\Evidence_Locker.UI\Evidence_Locker.UI.csproj" />
  </ItemGroup>

</Project>